name: job_search_app
description: "A job searching app using Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: 5.7.0  # For handling API requests
  get_it: ^7.7.0  # For dependency injection
  dartz: ^0.10.1  # For functional programming constructs
  dio_smart_retry: ^6.0.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  firebase_core: ^3.4.0
  ionicons: ^0.2.2
  intl: ^0.19.0
  share_plus: ^10.0.0
  path_provider: ^2.1.4
  get_storage: ^2.1.1
#  isar: ^3.1.0+1
#  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  build_runner: ^2.4.9
#  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/loading.json
    - assets/fake_response/search_jobs.json
