// Mocks generated by Mockito 5.4.4 from annotations
// in job_search_app/test/features/salary_estimation/data/repositories/salary_estimation_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:job_search_app/features/salary_estimation/data/datasources/salary_remote_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SalaryEstimationDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSalaryEstimationDatasource extends _i1.Mock
    implements _i2.SalaryEstimationDatasource {
  MockSalaryEstimationDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> getSalaryEstimation({
    required String? jobTitle,
    required String? location,
    String? radius,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSalaryEstimation,
          [],
          {
            #jobTitle: jobTitle,
            #location: location,
            #radius: radius,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}
